### ISSUE TITLE
Doesn't work anymore on anki newest version ( ⁨23.10.1)

### ISSUE THREAD

**Issue by ToscaBeijaert** [cjhoward/anki-set-font-size#6]
As i have stated above it doesn't work anymore :(
Please fix it! I have to look at these horrible tiny kanji in my browser and it's terrible hahahaha 😂

**Comment by ToscaBeijaert** [comment]
This is the debug info btw:

Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-12.2.1-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-12-20 08:49:15

When loading Set Font Size:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "/Users/tosca/Library/Application Support/Anki2/addons21/651521808/__init__.py", line 45, in <module>
    changeFontSize(mw.addonManager.getConfig(__name__))
  File "/Users/tosca/Library/Application Support/Anki2/addons21/651521808/__init__.py", line 43, in changeFontSize
    changeWebFontSize(font_size)
  File "/Users/tosca/Library/Application Support/Anki2/addons21/651521808/__init__.py", line 38, in changeWebFontSize
    wes.setFontSize(QWebEngineSettings.MinimumFontSize, font_size)
AttributeError: type object 'QWebEngineSettings' has no attribute 'MinimumFontSize'

**Comment by cjhoward** [comment]
Thanks! Resolved in 233f9aa528b6cf46b7c6f4171ce88a7d75debc0c and updated on AnkiWeb.
